# Configure the DNS server
dns:
  # What host to listen on
  host: 127.0.0.1

  # What port to listen on
  port: 1053

  # Upstream resolvers to use
  upstream:
    - 1.1.1.1:53
    - 1.0.0.1:53

  # Database to use to store records
  database: ./records.db

  # Disable one of the protocols
  # At least 1 must be enabled
  disable-tcp: false
  disable-udp: false

# Configure the HTTP API server
http:
  # What host to listen on
  host: 127.0.0.1

  # What port to listen on
  port: 8080

  # Primary admin user
  admin:
    name: DNS Admin
    username: admin
    password: admin

  # Disable the HTTP API
  disabled: false

  # Disable frontend interface
  disable-frontend: false
