version: "2.0"

services:
  dns:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8080:8080/tcp
      - 1053:53/tcp
      - 1053:53/udp
    volumes:
      - ./records.db:/records.db
      - ./config.yaml:/config.yaml:ro