version: "3.7"

services:
  dns:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - target: 8080
        published: 8080
        protocol: tcp
        mode: host
      - target: 53
        published: 1053
        protocol: tcp
        mode: host
      - target: 53
        published: 1053
        protocol: udp
        mode: host
    volumes:
      - type: bind
        source: ./records.db
        target: /records.db
        read_only: false
      - type: bind
        source: ./config.yaml
        target: /config.yaml
        read_only: true
